
// 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑
// 🛑 THIS IS AN AUTOGENERATED FILE - DO NOT EDIT DIRECTLY 🛑
// 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑

// @ts-nocheck
/* eslint-disable */
export type CoercedEnvSchema = {
  /**
   * **VARLOCK_ENV** 🔐 _sensitive_  
   * Auto-detected deployment environment (development, preview, staging, production, test)  
   */
  VARLOCK_ENV: string;
  
  /**
   * **VARLOCK_BRANCH** 🔐 _sensitive_  
   * Current git branch name. In CI, sourced from platform environment variables. Locally (non-CI), auto-detected via `git branch --show-current`.  
   */
  VARLOCK_BRANCH: string;
  
  /**
   * **BRANCH_NAME**  
   * -- Branch configuration (raw branch name, sanitized in plugin for resource names) --  
   */
  BRANCH_NAME: string;
  
  /** **VITE_BRANCH_NAME** */
  VITE_BRANCH_NAME: string;
  
  /**
   * **CDK_ENVIRONMENT**  
   * -- AWS CDK configuration --  
   */
  CDK_ENVIRONMENT: "dev" | "prod";
  
  /** **CDK_BUDGET_ALERT_EMAIL** */
  CDK_BUDGET_ALERT_EMAIL?: string;
  
  /** **CDK_MONITORING_ALERT_EMAIL** */
  CDK_MONITORING_ALERT_EMAIL?: string;
  
  /**
   * **CDK_DEPLOY_MAIL_INFRA**  
   * Maintainer-only: include MailInfraStack in CDK synthesis (never set during routine branch deploys)  
   */
  CDK_DEPLOY_MAIL_INFRA?: boolean;
  
  /**
   * **BETTER_AUTH_SECRET** 🔐 _sensitive_  
   * -- Better Auth configuration --  
   */
  BETTER_AUTH_SECRET: string;
  
  /**
   * **SAMS_API_KEY** 🔐 _sensitive_  
   * -- SAMS API credentials --  
   */
  SAMS_API_KEY: string;
  
  /**
   * **BEHOLD_FEED_URL** 🔐 _sensitive_  
   * -- Behold Instagram feed --  
   */
  BEHOLD_FEED_URL: string;
  
  /** **SENTRY_AUTH_TOKEN** 🔐 _sensitive_ */
  SENTRY_AUTH_TOKEN: string;
  
  /** **SENTRY_ENVIRONMENT** */
  SENTRY_ENVIRONMENT: "dev" | "prod";
  
};

type _CoercedEnvSchema_d8bae827 = CoercedEnvSchema;

declare module 'varlock/env' {
  export interface TypedEnvSchema extends Readonly<_CoercedEnvSchema_d8bae827> {}
  export interface PublicTypedEnvSchema extends Readonly<Pick<_CoercedEnvSchema_d8bae827, 'BRANCH_NAME' | 'VITE_BRANCH_NAME' | 'CDK_ENVIRONMENT' | 'CDK_BUDGET_ALERT_EMAIL' | 'CDK_MONITORING_ALERT_EMAIL' | 'CDK_DEPLOY_MAIL_INFRA' | 'SENTRY_ENVIRONMENT'>> {}
}


export type EnvSchemaAsStrings = {
  [Property in keyof CoercedEnvSchema]:
    CoercedEnvSchema[Property] extends string ? CoercedEnvSchema[Property]
      : (CoercedEnvSchema[Property] extends boolean ? ('true' | 'false') : string)
};

type _EnvSchemaAsStrings_d8bae827 = EnvSchemaAsStrings;
declare global {

  // add types for global import.meta.env
  interface ImportMetaEnv extends _EnvSchemaAsStrings_d8bae827 {}
  interface ImportMeta {
    readonly env: ImportMetaEnv;
  }

  // add types for global process.env
  namespace NodeJS {
    interface ProcessEnv extends _EnvSchemaAsStrings_d8bae827 {}
  }
}