/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as IcsTeamSlugRouteImport } from './routes/ics/$teamSlug'
import { Route as AdminOtpLoginRouteImport } from './routes/admin/otp-login'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminLayoutRouteImport } from './routes/admin/_layout'
import { Route as LayoutTeamsRouteImport } from './routes/_layout/teams'
import { Route as LayoutTabelleRouteImport } from './routes/_layout/tabelle'
import { Route as LayoutMemberRouteImport } from './routes/_layout/member'
import { Route as LayoutMatchesRouteImport } from './routes/_layout/matches'
import { Route as LayoutImpressumRouteImport } from './routes/_layout/impressum'
import { Route as LayoutDatenschutzRouteImport } from './routes/_layout/datenschutz'
import { Route as LayoutBrandRouteImport } from './routes/_layout/brand'
import { Route as AdminLayoutIndexRouteImport } from './routes/admin/_layout/index'
import { Route as LayoutTeamsIndexRouteImport } from './routes/_layout/teams.index'
import { Route as LayoutMatchesIndexRouteImport } from './routes/_layout/matches.index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminLayoutTeamsRouteImport } from './routes/admin/_layout/teams'
import { Route as AdminLayoutSponsorsRouteImport } from './routes/admin/_layout/sponsors'
import { Route as AdminLayoutSamsRouteImport } from './routes/admin/_layout/sams'
import { Route as AdminLayoutMembersRouteImport } from './routes/admin/_layout/members'
import { Route as AdminLayoutLocationsRouteImport } from './routes/admin/_layout/locations'
import { Route as LayoutTeamsSlugRouteImport } from './routes/_layout/teams.$slug'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const IcsTeamSlugRoute = IcsTeamSlugRouteImport.update({
  id: '/ics/$teamSlug',
  path: '/ics/$teamSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOtpLoginRoute = AdminOtpLoginRouteImport.update({
  id: '/admin/otp-login',
  path: '/admin/otp-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/admin/_layout',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutTeamsRoute = LayoutTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTabelleRoute = LayoutTabelleRouteImport.update({
  id: '/tabelle',
  path: '/tabelle',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMemberRoute = LayoutMemberRouteImport.update({
  id: '/member',
  path: '/member',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMatchesRoute = LayoutMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutImpressumRoute = LayoutImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDatenschutzRoute = LayoutDatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBrandRoute = LayoutBrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => LayoutRoute,
} as any)
const AdminLayoutIndexRoute = AdminLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const LayoutTeamsIndexRoute = LayoutTeamsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutTeamsRoute,
} as any)
const LayoutMatchesIndexRoute = LayoutMatchesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutMatchesRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutTeamsRoute = AdminLayoutTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutSponsorsRoute = AdminLayoutSponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutSamsRoute = AdminLayoutSamsRouteImport.update({
  id: '/sams',
  path: '/sams',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutMembersRoute = AdminLayoutMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutLocationsRoute = AdminLayoutLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const LayoutTeamsSlugRoute = LayoutTeamsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LayoutTeamsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/brand': typeof LayoutBrandRoute
  '/datenschutz': typeof LayoutDatenschutzRoute
  '/impressum': typeof LayoutImpressumRoute
  '/matches': typeof LayoutMatchesRouteWithChildren
  '/member': typeof LayoutMemberRoute
  '/tabelle': typeof LayoutTabelleRoute
  '/teams': typeof LayoutTeamsRouteWithChildren
  '/admin': typeof AdminLayoutRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/otp-login': typeof AdminOtpLoginRoute
  '/ics/$teamSlug': typeof IcsTeamSlugRoute
  '/teams/$slug': typeof LayoutTeamsSlugRoute
  '/admin/locations': typeof AdminLayoutLocationsRoute
  '/admin/members': typeof AdminLayoutMembersRoute
  '/admin/sams': typeof AdminLayoutSamsRoute
  '/admin/sponsors': typeof AdminLayoutSponsorsRoute
  '/admin/teams': typeof AdminLayoutTeamsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/matches/': typeof LayoutMatchesIndexRoute
  '/teams/': typeof LayoutTeamsIndexRoute
  '/admin/': typeof AdminLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/brand': typeof LayoutBrandRoute
  '/datenschutz': typeof LayoutDatenschutzRoute
  '/impressum': typeof LayoutImpressumRoute
  '/member': typeof LayoutMemberRoute
  '/tabelle': typeof LayoutTabelleRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/otp-login': typeof AdminOtpLoginRoute
  '/ics/$teamSlug': typeof IcsTeamSlugRoute
  '/': typeof LayoutIndexRoute
  '/teams/$slug': typeof LayoutTeamsSlugRoute
  '/admin/locations': typeof AdminLayoutLocationsRoute
  '/admin/members': typeof AdminLayoutMembersRoute
  '/admin/sams': typeof AdminLayoutSamsRoute
  '/admin/sponsors': typeof AdminLayoutSponsorsRoute
  '/admin/teams': typeof AdminLayoutTeamsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/matches': typeof LayoutMatchesIndexRoute
  '/teams': typeof LayoutTeamsIndexRoute
  '/admin': typeof AdminLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/brand': typeof LayoutBrandRoute
  '/_layout/datenschutz': typeof LayoutDatenschutzRoute
  '/_layout/impressum': typeof LayoutImpressumRoute
  '/_layout/matches': typeof LayoutMatchesRouteWithChildren
  '/_layout/member': typeof LayoutMemberRoute
  '/_layout/tabelle': typeof LayoutTabelleRoute
  '/_layout/teams': typeof LayoutTeamsRouteWithChildren
  '/admin/_layout': typeof AdminLayoutRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/otp-login': typeof AdminOtpLoginRoute
  '/ics/$teamSlug': typeof IcsTeamSlugRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/teams/$slug': typeof LayoutTeamsSlugRoute
  '/admin/_layout/locations': typeof AdminLayoutLocationsRoute
  '/admin/_layout/members': typeof AdminLayoutMembersRoute
  '/admin/_layout/sams': typeof AdminLayoutSamsRoute
  '/admin/_layout/sponsors': typeof AdminLayoutSponsorsRoute
  '/admin/_layout/teams': typeof AdminLayoutTeamsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_layout/matches/': typeof LayoutMatchesIndexRoute
  '/_layout/teams/': typeof LayoutTeamsIndexRoute
  '/admin/_layout/': typeof AdminLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brand'
    | '/datenschutz'
    | '/impressum'
    | '/matches'
    | '/member'
    | '/tabelle'
    | '/teams'
    | '/admin'
    | '/admin/login'
    | '/admin/otp-login'
    | '/ics/$teamSlug'
    | '/teams/$slug'
    | '/admin/locations'
    | '/admin/members'
    | '/admin/sams'
    | '/admin/sponsors'
    | '/admin/teams'
    | '/api/auth/$'
    | '/matches/'
    | '/teams/'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/brand'
    | '/datenschutz'
    | '/impressum'
    | '/member'
    | '/tabelle'
    | '/admin/login'
    | '/admin/otp-login'
    | '/ics/$teamSlug'
    | '/'
    | '/teams/$slug'
    | '/admin/locations'
    | '/admin/members'
    | '/admin/sams'
    | '/admin/sponsors'
    | '/admin/teams'
    | '/api/auth/$'
    | '/matches'
    | '/teams'
    | '/admin'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/brand'
    | '/_layout/datenschutz'
    | '/_layout/impressum'
    | '/_layout/matches'
    | '/_layout/member'
    | '/_layout/tabelle'
    | '/_layout/teams'
    | '/admin/_layout'
    | '/admin/login'
    | '/admin/otp-login'
    | '/ics/$teamSlug'
    | '/_layout/'
    | '/_layout/teams/$slug'
    | '/admin/_layout/locations'
    | '/admin/_layout/members'
    | '/admin/_layout/sams'
    | '/admin/_layout/sponsors'
    | '/admin/_layout/teams'
    | '/api/auth/$'
    | '/_layout/matches/'
    | '/_layout/teams/'
    | '/admin/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  AdminLayoutRoute: typeof AdminLayoutRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AdminOtpLoginRoute: typeof AdminOtpLoginRoute
  IcsTeamSlugRoute: typeof IcsTeamSlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/ics/$teamSlug': {
      id: '/ics/$teamSlug'
      path: '/ics/$teamSlug'
      fullPath: '/ics/$teamSlug'
      preLoaderRoute: typeof IcsTeamSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/otp-login': {
      id: '/admin/otp-login'
      path: '/admin/otp-login'
      fullPath: '/admin/otp-login'
      preLoaderRoute: typeof AdminOtpLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/teams': {
      id: '/_layout/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof LayoutTeamsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tabelle': {
      id: '/_layout/tabelle'
      path: '/tabelle'
      fullPath: '/tabelle'
      preLoaderRoute: typeof LayoutTabelleRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/member': {
      id: '/_layout/member'
      path: '/member'
      fullPath: '/member'
      preLoaderRoute: typeof LayoutMemberRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/matches': {
      id: '/_layout/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof LayoutMatchesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/impressum': {
      id: '/_layout/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof LayoutImpressumRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/datenschutz': {
      id: '/_layout/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof LayoutDatenschutzRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/brand': {
      id: '/_layout/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof LayoutBrandRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/admin/_layout/': {
      id: '/admin/_layout/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminLayoutIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/_layout/teams/': {
      id: '/_layout/teams/'
      path: '/'
      fullPath: '/teams/'
      preLoaderRoute: typeof LayoutTeamsIndexRouteImport
      parentRoute: typeof LayoutTeamsRoute
    }
    '/_layout/matches/': {
      id: '/_layout/matches/'
      path: '/'
      fullPath: '/matches/'
      preLoaderRoute: typeof LayoutMatchesIndexRouteImport
      parentRoute: typeof LayoutMatchesRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout/teams': {
      id: '/admin/_layout/teams'
      path: '/teams'
      fullPath: '/admin/teams'
      preLoaderRoute: typeof AdminLayoutTeamsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/sponsors': {
      id: '/admin/_layout/sponsors'
      path: '/sponsors'
      fullPath: '/admin/sponsors'
      preLoaderRoute: typeof AdminLayoutSponsorsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/sams': {
      id: '/admin/_layout/sams'
      path: '/sams'
      fullPath: '/admin/sams'
      preLoaderRoute: typeof AdminLayoutSamsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/members': {
      id: '/admin/_layout/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminLayoutMembersRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/locations': {
      id: '/admin/_layout/locations'
      path: '/locations'
      fullPath: '/admin/locations'
      preLoaderRoute: typeof AdminLayoutLocationsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/_layout/teams/$slug': {
      id: '/_layout/teams/$slug'
      path: '/$slug'
      fullPath: '/teams/$slug'
      preLoaderRoute: typeof LayoutTeamsSlugRouteImport
      parentRoute: typeof LayoutTeamsRoute
    }
  }
}

interface LayoutMatchesRouteChildren {
  LayoutMatchesIndexRoute: typeof LayoutMatchesIndexRoute
}

const LayoutMatchesRouteChildren: LayoutMatchesRouteChildren = {
  LayoutMatchesIndexRoute: LayoutMatchesIndexRoute,
}

const LayoutMatchesRouteWithChildren = LayoutMatchesRoute._addFileChildren(
  LayoutMatchesRouteChildren,
)

interface LayoutTeamsRouteChildren {
  LayoutTeamsSlugRoute: typeof LayoutTeamsSlugRoute
  LayoutTeamsIndexRoute: typeof LayoutTeamsIndexRoute
}

const LayoutTeamsRouteChildren: LayoutTeamsRouteChildren = {
  LayoutTeamsSlugRoute: LayoutTeamsSlugRoute,
  LayoutTeamsIndexRoute: LayoutTeamsIndexRoute,
}

const LayoutTeamsRouteWithChildren = LayoutTeamsRoute._addFileChildren(
  LayoutTeamsRouteChildren,
)

interface LayoutRouteChildren {
  LayoutBrandRoute: typeof LayoutBrandRoute
  LayoutDatenschutzRoute: typeof LayoutDatenschutzRoute
  LayoutImpressumRoute: typeof LayoutImpressumRoute
  LayoutMatchesRoute: typeof LayoutMatchesRouteWithChildren
  LayoutMemberRoute: typeof LayoutMemberRoute
  LayoutTabelleRoute: typeof LayoutTabelleRoute
  LayoutTeamsRoute: typeof LayoutTeamsRouteWithChildren
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutBrandRoute: LayoutBrandRoute,
  LayoutDatenschutzRoute: LayoutDatenschutzRoute,
  LayoutImpressumRoute: LayoutImpressumRoute,
  LayoutMatchesRoute: LayoutMatchesRouteWithChildren,
  LayoutMemberRoute: LayoutMemberRoute,
  LayoutTabelleRoute: LayoutTabelleRoute,
  LayoutTeamsRoute: LayoutTeamsRouteWithChildren,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface AdminLayoutRouteChildren {
  AdminLayoutLocationsRoute: typeof AdminLayoutLocationsRoute
  AdminLayoutMembersRoute: typeof AdminLayoutMembersRoute
  AdminLayoutSamsRoute: typeof AdminLayoutSamsRoute
  AdminLayoutSponsorsRoute: typeof AdminLayoutSponsorsRoute
  AdminLayoutTeamsRoute: typeof AdminLayoutTeamsRoute
  AdminLayoutIndexRoute: typeof AdminLayoutIndexRoute
}

const AdminLayoutRouteChildren: AdminLayoutRouteChildren = {
  AdminLayoutLocationsRoute: AdminLayoutLocationsRoute,
  AdminLayoutMembersRoute: AdminLayoutMembersRoute,
  AdminLayoutSamsRoute: AdminLayoutSamsRoute,
  AdminLayoutSponsorsRoute: AdminLayoutSponsorsRoute,
  AdminLayoutTeamsRoute: AdminLayoutTeamsRoute,
  AdminLayoutIndexRoute: AdminLayoutIndexRoute,
}

const AdminLayoutRouteWithChildren = AdminLayoutRoute._addFileChildren(
  AdminLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  AdminLayoutRoute: AdminLayoutRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AdminOtpLoginRoute: AdminOtpLoginRoute,
  IcsTeamSlugRoute: IcsTeamSlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
